### ISSUE TITLE
how to populate tree view with a data from view model?

### ISSUE THREAD

**Issue by NikasZalias** [jakebonk/DraggableTreeViewExample#2]
I'm using MvvmCross for my android application. Is it possible to populate draggable tree view with data from viewmodel??

**Comment by jakebonk** [comment]
I've never used MvvmCross but from my limited understanding of it, it is a plugin in for Xamarin. Since this is written in Java you would have to bind the library to Xamarin. I think this link could help with the process : https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/
